name: validate-topics
run-name: topic validation
on: [push]
jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: logging
        run: echo "validating topics..."

      - name: validation
        run: bash validate.sh topics --quiet
