name: validate-topics
run-name: ${{ github.actor }} validates topics
on: [push]
jobs:
  validate-topics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash ./${{ github.workspace }}/validate.sh topics --quiet
